//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace REP001.Comun.WebClient.MVC.PersonWebServiceReference {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PersonInfo", Namespace="http://schemas.datacontract.org/2004/07/REP001.Comun.WebHost")]
    [System.SerializableAttribute()]
    public partial class PersonInfo : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string Name {
            get {
                return this.NameField;
            }
            set {
                if ((object.ReferenceEquals(this.NameField, value) != true)) {
                    this.NameField = value;
                    this.RaisePropertyChanged("Name");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="PersonWebServiceReference.IPersonWebService")]
    public interface IPersonWebService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonWebService/DoSearchByName", ReplyAction="http://tempuri.org/IPersonWebService/DoSearchByNameResponse")]
        REP001.Comun.WebClient.MVC.PersonWebServiceReference.PersonInfo[] DoSearchByName(string name);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IPersonWebService/DoSearchByName", ReplyAction="http://tempuri.org/IPersonWebService/DoSearchByNameResponse")]
        System.Threading.Tasks.Task<REP001.Comun.WebClient.MVC.PersonWebServiceReference.PersonInfo[]> DoSearchByNameAsync(string name);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IPersonWebServiceChannel : REP001.Comun.WebClient.MVC.PersonWebServiceReference.IPersonWebService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PersonWebServiceClient : System.ServiceModel.ClientBase<REP001.Comun.WebClient.MVC.PersonWebServiceReference.IPersonWebService>, REP001.Comun.WebClient.MVC.PersonWebServiceReference.IPersonWebService {
        
        public PersonWebServiceClient() {
        }
        
        public PersonWebServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PersonWebServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersonWebServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PersonWebServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public REP001.Comun.WebClient.MVC.PersonWebServiceReference.PersonInfo[] DoSearchByName(string name) {
            return base.Channel.DoSearchByName(name);
        }
        
        public System.Threading.Tasks.Task<REP001.Comun.WebClient.MVC.PersonWebServiceReference.PersonInfo[]> DoSearchByNameAsync(string name) {
            return base.Channel.DoSearchByNameAsync(name);
        }
    }
}
