// <auto-generated />
namespace REP001.Comun.BO.Context.Migrations
{
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    public sealed partial class Initial5 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Initial5));
        
        string IMigrationMetadata.Id
        {
            get { return "201306051608383_Initial5"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
